// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WalletGasSpent {
    #[prost(uint64, tag="1")]
    pub lamports: u64,
}
// @@protoc_insertion_point(module)
